mqtt:
  host: localhost
  port: 1883
  connection:
    keepalive: 15
    retry_limit: 30
    reconnect_interval: 10
homeassistant:
  enabled: true
  discovery_prefix: homeassistant
devices:
  di_3_02:
    friendly_name: "Workspace - Switch up"
  di_3_03:
    friendly_name: "Workspace - Switch down"
covers:
  blinds:
    - friendly_name: "Workspace - Blind 1"
      topic_name: workspace_1
      runtime: 35.5
      circuit_up: ro_3_03
      circuit_down: ro_3_02
logging:
  logger: systemd
  level: info
