device_name: Unipi
mqtt:
  host: localhost
  port: 1883
  connection:
    keepalive: 15
    retry_limit: 30
    reconnect_interval: 10
homeassistant:
  discovery_prefix: homeassistant
plugins:
  devices:
    enabled:
      - di_3_02
      - di_3_03
      - ro_3_02
      - ro_3_03
    mapping:
      di_3_02:
        friendly_name: "Workspace - Switch up"
      di_3_03:
        friendly_name: "Workspace - Switch down"
  covers:
    blinds:
      - friendly_name: "Workspace - Blind 1"
        topic_name: workspace_1
        runtime: 35.5
        port_up: ro_3_03
        port_down: ro_3_02
logging:
  logger: systemd
  level: info
