blueprint:
  name: Cover control
  description: Short and Long click actions to control the cover
  domain: automation
  input:
    binary_sensor_down_id:
      name: Binary sensor entity (down)
      description: The binary sensor used to close the cover
      selector:
        entity:
          domain: binary_sensor
    binary_sensor_up_id:
      name: Binary sensor entity (up)
      description: The binary sensor used to open the cover
      selector:
        entity:
          domain: binary_sensor
    cover_id:
      name: Cover
      description: Select cover to control
      selector:
        entity:
          domain: cover
    has_tilt:
      name: Tilt
      description: Enable tilt position control
      default: false
      selector:
        boolean:
    tilt_position:
      name: Tilt change position
      description: The value in percent for tilt position changes
      default: 20
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: "%"
          step: 1.0
          mode: slider
trigger:
  - platform: state
    id: cover_closing
    entity_id: !input "binary_sensor_down_id"
    to: "on"
  - platform: state
    entity_id: !input "binary_sensor_up_id"
    to: "on"
    id: cover_opening
action:
  - variables:
      binary_sensor_down_id: !input "binary_sensor_down_id"
      binary_sensor_up_id: !input "binary_sensor_up_id"
      cover_id: !input "cover_id"
      has_tilt: !input "has_tilt"
      tilt_position: !input "tilt_position"
  - choose:
      - conditions:
          - condition: trigger
            id: cover_closing
        sequence:
          - wait_template: "{{ is_state(binary_sensor_down_id, 'off') }}"
            timeout: "0.5"
            continue_on_timeout: true
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not wait.completed }}"
                sequence:
                  - service: cover.close_cover
                    target:
                      entity_id: !input "cover_id"
            default:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ is_state(cover_id, 'open') }}"
                      - condition: or
                        conditions:
                          - condition: template
                            value_template: "{{ not has_tilt }}"
                          - condition: template
                            value_template: "{{ state_attr(cover_id, 'current_position') == 100 }}"
                    sequence:
                      - service: cover.close_cover
                        target:
                          entity_id: !input "cover_id"
                  - conditions:
                      - condition: template
                        value_template: "{{ is_state(cover_id, 'opening') }}"
                    sequence:
                      - service: cover.stop_cover
                        target:
                          entity_id: !input "cover_id"
                  - conditions:
                      - condition: template
                        value_template: "{{ has_tilt }}"
                      - condition: template
                        value_template: "{{ is_state(cover_id, 'open') }}"
                      - condition: template
                        value_template: "{{ state_attr(cover_id, 'current_position') < 100 }}"
                      - condition: template
                        value_template: "{{ state_attr(cover_id, 'current_tilt_position') > 0 }}"
                    sequence:
                      - service: cover.set_cover_tilt_position
                        target:
                          entity_id: !input "cover_id"
                        data:
                          tilt_position: >-
                            {% set tilt_position_value = state_attr(cover_id, 'current_tilt_position')|int - tilt_position %}

                            {% if tilt_position_value < 0 %}
                              0
                            {% else %}
                              {{ tilt_position_value }}
                            {% endif %}
      - conditions:
          - condition: trigger
            id: cover_opening
        sequence:
          - wait_template: "{{ is_state(binary_sensor_up_id, 'off') }}"
            timeout: "0.5"
            continue_on_timeout: true
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ not wait.completed }}"
                sequence:
                  - service: cover.open_cover
                    target:
                      entity_id: !input "cover_id"
            default:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ not has_tilt }}"
                      - condition: template
                        value_template: "{{ not is_state(cover_id, 'closing') }}"
                      - condition: template
                        value_template: "{{ state_attr(cover_id, 'current_position') < 100 }}"
                    sequence:
                      - service: cover.open_cover
                        target:
                          entity_id: !input "cover_id"
                  - conditions:
                      - condition: template
                        value_template: "{{ is_state(cover_id, 'closing') }}"
                    sequence:
                      - service: cover.stop_cover
                        target:
                          entity_id: !input "cover_id"
                  - conditions:
                      - condition: template
                        value_template: "{{ has_tilt }}"
                      - condition: template
                        value_template: "{{ is_state(cover_id, 'open')}}"
                      - condition: template
                        value_template: "{{ state_attr(cover_id, 'current_position') < 100 }}"
                      - condition: template
                        value_template: "{{ state_attr(cover_id, 'current_tilt_position') < 100 }}"
                    sequence:
                      - service: cover.set_cover_tilt_position
                        target:
                          entity_id: !input "cover_id"
                        data:
                          tilt_position: >-
                            {% set tilt_position_value = state_attr(cover_id, 'current_tilt_position')|int + tilt_position %}

                            {% if tilt_position_value > 100 %}
                              100
                            {% else %}
                              {{ tilt_position_value }}
                            {% endif %}
                  - conditions:
                      - condition: template
                        value_template: "{{ has_tilt }}"
                      - condition: template
                        value_template: "{{ is_state(cover_id, 'closed') }}"
                    sequence:
                      - service: cover.set_cover_tilt_position
                        target:
                          entity_id: !input "cover_id"
                        data:
                          tilt_position: >-
                            {% set tilt_position_value = state_attr(cover_id, 'current_tilt_position')|int + tilt_position %}

                            {% if tilt_position_value > 100 %}
                              100
                            {% else %}
                              {{ tilt_position_value }}
                            {% endif %}
    default: []
