mqtt:
  host: localhost
  port: 1883
  connection:
    keepalive: 15
    retry_limit: 30
    reconnect_interval: 10
ow:
  - owbus: /dev/i2c-1
    interval: 3
    scan_interval: 300
ow_devices:
  - bus: 1
    address: 264851680200002E
    type: DS2438
    interval: 1
homeassistant:
  enabled: true
  discovery_prefix: homeassistant
features:
  di_3_02:
    friendly_name: "Workspace - Switch up"
  di_3_03:
    friendly_name: "Workspace - Switch down"
covers:
  - friendly_name: "Workspace - Blind 1"
    cover_type: "blind"
    topic_name: workspace_1
    full_open_time: 35.5
    full_close_time: 35.5
    tilt_change_time: 1.5
    circuit_up: ro_3_03
    circuit_down: ro_3_02
logging:
  level: info
