name: Build

on:
  workflow_call:
    inputs:
      latest-python-version:
        required: True
        type: string
      package-name:
        required: True
        type: string
      package-version:
        required: True
        type: string
      binary-files:
        required: True
        type: string

jobs:
  build-python-package:
    name: Build python package
    uses: superbox-dev/python-package-workflows/.github/workflows/build-python-package.yml@main
    with:
      latest-python-version: ${{ inputs.latest-python-version }}
      package-version: ${{ inputs.package-version }}

  build-binary-files:
    name: Build binary files
    uses: superbox-dev/python-package-workflows/.github/workflows/build-binary-files.yml@main
    with:
      package-version: ${{ inputs.package-version }}
      binary-files: ${{ inputs.binary-files }}

  build-opkg-package:
    name: Build OPKG package
    needs:
      - build-binary-files
    uses: superbox-dev/python-package-workflows/.github/workflows/build-opkg-package.yml@main
    with:
      latest-python-version: ${{ inputs.latest-python-version }}
      package-name: ${{ inputs.package-name }}
      package-version: ${{ inputs.package-version }}
