name: Pylint

on: [push]

jobs:
  runs-on: ubuntu-18.04
  
  steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq upgrade
        sudo apt install python3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
