name: Upload Python Package

on:
  create:
    branches:
      - '!*'
    tags:
      - '^[0-9]+\.[0-9]+\.[0-9]+$'

jobs:
  check-tag:
    runs-on: ubuntu-latest
    outputs:
      release-type: ${{ steps.check-tag.outputs.run_jobs }}
    steps:
      - name: check tag ${{ github.ref }}
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=run_jobs::release
          elif [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+\-beta[0-9]$ ]]; then
            echo ::set-output name=run_jobs::prerelease
          fi

  deploy:
    needs: [check-tag]
    if: needs.check_tag.outputs.release-type == 'release' or needs.check_tag.outputs.release-type == 'prerelease'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Check Tag
      id: check-tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo ::set-output name=match::release
        elif [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+\-beta[0-9]$ ]]; then
          echo ::set-output name=match::prerelease
        fi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish test package
      if: needs.check_tag.outputs.release-type == 'prerelease'
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
    - name: Publish package
      if: needs.check_tag.outputs.release-type == 'release'
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        # password: ${{ secrets.PYPI_API_TOKEN }}
